### ISSUE TITLE
Tenzies Game 

### ISSUE THREAD

**Issue by sarapapa-sp** [Puja7629/HACTOBERFEST2022#17]
Adding the tezies game , made using ReactJs

**Comment by sarapapa-sp** [comment]
@Puja7629  can you assign this to me .

**Comment by Puja7629** [comment]
> @Puja7629 can you assign this to me .

Assigned, Go ahead @sarapapa-sp .

**Comment by Puja7629** [comment]
> @Puja7629 can you assign this to me .

Once you are done you can send your PR and I will review it. Make sure you read our README for sending the PR(Only folder with meaningful name would be accepted rather than files). Closing this issue as of now. 
Happy Coding :)
